import {
  Consultation,
  Patient,
  Doctor,
  MedicalRecord,
  PatientProfile,
  ConsultationReminder,
  AdminConsultation,
  AdminMedicalRecord,
} from '../types';

// ===== DADOS MOCKADOS DE CONSULTAS =====

export const MOCK_CONSULTATIONS_MEDICO = [
  {
    _id: '1',
    patientId: 'p1',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    patientPhone: '(11) 99999-1111',
    date: '2024-01-15',
    time: '09:00',
    status: 'completed',
    notes: 'Paciente relatou dor de cabeça persistente há 3 dias.',
    diagnosis: 'Cefaleia tensional',
    prescription: 'Paracetamol 500mg - 1 comprimido a cada 6 horas por 3 dias',
    symptoms: 'Dor de cabeça, tensão muscular',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    _id: '2',
    patientId: 'p2',
    patientName: 'João Santos',
    patientEmail: 'joao@email.com',
    patientPhone: '(11) 99999-2222',
    date: '2024-01-15',
    time: '14:30',
    status: 'scheduled',
    symptoms: 'Dor abdominal, náuseas',
    createdAt: '2024-01-12T14:00:00Z',
  },
  {
    _id: '3',
    patientId: 'p3',
    patientName: 'Ana Costa',
    patientEmail: 'ana@email.com',
    patientPhone: '(11) 99999-3333',
    date: '2024-01-16',
    time: '10:00',
    status: 'confirmed',
    symptoms: 'Febre, tosse seca',
    createdAt: '2024-01-13T09:30:00Z',
  },
  {
    _id: '4',
    patientId: 'p4',
    patientName: 'Pedro Oliveira',
    patientEmail: 'pedro@email.com',
    patientPhone: '(11) 99999-4444',
    date: '2024-01-17',
    time: '16:00',
    status: 'scheduled',
    symptoms: 'Dor nas costas, dificuldade para dormir',
    createdAt: '2024-01-14T11:15:00Z',
  },
  {
    _id: '5',
    patientId: 'p5',
    patientName: 'Lucia Ferreira',
    patientEmail: 'lucia@email.com',
    patientPhone: '(11) 99999-5555',
    date: '2024-01-14',
    time: '11:00',
    status: 'cancelled',
    notes: 'Paciente cancelou por motivos pessoais',
    createdAt: '2024-01-11T16:45:00Z',
  },
  {
    _id: '6',
    patientId: 'p6',
    patientName: 'Carlos Mendes',
    patientEmail: 'carlos@email.com',
    patientPhone: '(11) 99999-6666',
    date: '2024-01-18',
    time: '08:30',
    status: 'scheduled',
    symptoms: 'Dor no peito, falta de ar',
    createdAt: '2024-01-15T13:20:00Z',
  },
];

export const MOCK_CONSULTATIONS_PACIENTE = [
  {
    _id: '1',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    doctorName: 'Dr. Carlos Mendes',
    doctorEmail: 'carlos.mendes@clinica.com',
    doctorPhone: '(11) 99999-0001',
    date: '2024-01-15',
    time: '09:00',
    status: 'completed',
    symptoms: 'Dor de cabeça, tensão muscular',
    notes:
      'Consulta realizada com sucesso. Paciente apresentou melhora dos sintomas.',
    diagnosis: 'Cefaleia tensional',
    prescription: 'Paracetamol 500mg - 1 comprimido a cada 6 horas por 3 dias',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    _id: '2',
    patientName: 'João Santos',
    patientEmail: 'joao@email.com',
    doctorName: 'Dr. Ana Silva',
    doctorEmail: 'ana.silva@clinica.com',
    doctorPhone: '(11) 99999-0002',
    date: '2024-01-20',
    time: '14:30',
    status: 'scheduled',
    symptoms: 'Dor nas costas',
    createdAt: '2024-01-12T14:00:00Z',
  },
  {
    _id: '3',
    patientName: 'Ana Costa',
    patientEmail: 'ana@email.com',
    doctorName: 'Dr. Pedro Santos',
    doctorEmail: 'pedro.santos@clinica.com',
    doctorPhone: '(11) 99999-0003',
    date: '2024-01-25',
    time: '10:00',
    status: 'confirmed',
    symptoms: 'Febre, tosse seca',
    createdAt: '2024-01-13T09:30:00Z',
  },
  {
    _id: '4',
    patientName: 'Pedro Oliveira',
    patientEmail: 'pedro@email.com',
    doctorName: 'Dr. Lucia Ferreira',
    doctorEmail: 'lucia.ferreira@clinica.com',
    doctorPhone: '(11) 99999-0004',
    date: '2024-01-30',
    time: '16:00',
    status: 'scheduled',
    symptoms: 'Dor abdominal',
    createdAt: '2024-01-14T11:15:00Z',
  },
  {
    _id: '5',
    patientName: 'Lucia Ferreira',
    patientEmail: 'lucia@email.com',
    doctorName: 'Dr. Roberto Costa',
    doctorEmail: 'roberto.costa@clinica.com',
    doctorPhone: '(11) 99999-0005',
    date: '2024-01-18',
    time: '11:00',
    status: 'cancelled',
    symptoms: 'Dor de cabeça',
    notes: 'Consulta cancelada pelo paciente',
    createdAt: '2024-01-11T16:45:00Z',
  },
  {
    _id: '6',
    patientName: 'Carlos Mendes',
    patientEmail: 'carlos@email.com',
    doctorName: 'Dr. Fernanda Lima',
    doctorEmail: 'fernanda.lima@clinica.com',
    doctorPhone: '(11) 99999-0006',
    date: '2024-02-05',
    time: '08:30',
    status: 'scheduled',
    symptoms: 'Dor no peito, falta de ar',
    createdAt: '2024-01-15T13:20:00Z',
  },
];

export const MOCK_CONSULTATIONS_ADMIN = [
  {
    _id: '1',
    patient: { name: 'João Silva', email: 'joao@email.com' },
    doctor: { name: 'Dr. Maria Santos', email: 'maria@clinic.com' },
    date: '2024-01-15',
    time: '14:00',
    status: 'completed',
    type: 'Consulta Regular',
    notes: 'Paciente apresentou melhora significativa',
  },
  {
    _id: '2',
    patient: { name: 'Ana Costa', email: 'ana@email.com' },
    doctor: { name: 'Dr. Carlos Oliveira', email: 'carlos@clinic.com' },
    date: '2024-01-16',
    time: '10:30',
    status: 'scheduled',
    type: 'Primeira Consulta',
  },
  {
    _id: '3',
    patient: { name: 'Pedro Lima', email: 'pedro@email.com' },
    doctor: { name: 'Dr. Maria Santos', email: 'maria@clinic.com' },
    date: '2024-01-14',
    time: '16:00',
    status: 'cancelled',
    type: 'Retorno',
    notes: 'Paciente cancelou por motivos pessoais',
  },
];

// ===== DADOS MOCKADOS DE PACIENTES =====

export const MOCK_PATIENTS = [
  {
    _id: 'p1',
    name: 'Maria Silva',
    email: 'maria@email.com',
    phone: '(11) 99999-1111',
    dateOfBirth: '1985-03-15',
    gender: 'female',
    address: 'Rua das Flores, 123 - São Paulo, SP',
    bloodType: 'A+',
    height: 165,
    weight: 62,
    emergencyContact: {
      name: 'João Silva',
      phone: '(11) 99999-0000',
      relationship: 'Esposo',
    },
    medicalHistory: [
      {
        _id: 'mh1',
        date: '2024-01-15',
        diagnosis: 'Cefaleia tensional',
        treatment: 'Analgésicos e relaxamento muscular',
        prescription:
          'Paracetamol 500mg - 1 comprimido a cada 6 horas por 3 dias',
        notes:
          'Paciente relatou dor de cabeça persistente há 3 dias. Recomendado evitar estresse.',
        doctor: 'Dr. Carlos Mendes',
        createdAt: '2024-01-15T10:00:00Z',
      },
      {
        _id: 'mh2',
        date: '2023-12-10',
        diagnosis: 'Resfriado comum',
        treatment: 'Repouso e hidratação',
        prescription: 'Vitamina C e paracetamol conforme necessário',
        notes: 'Sintomas leves, sem complicações.',
        doctor: 'Dr. Carlos Mendes',
        createdAt: '2023-12-10T14:30:00Z',
      },
    ],
    consultations: [
      {
        _id: 'c1',
        patientName: 'Maria Silva',
        patientEmail: 'maria@email.com',
        doctorName: 'Dr. Carlos Mendes',
        doctorEmail: 'carlos.mendes@clinica.com',
        doctorPhone: '(11) 99999-0001',
        date: '2024-01-15',
        time: '09:00',
        status: 'completed',
        symptoms: 'Dor de cabeça, tensão muscular',
        notes: 'Consulta realizada com sucesso',
      },
      {
        _id: 'c2',
        patientName: 'Maria Silva',
        patientEmail: 'maria@email.com',
        doctorName: 'Dr. Ana Silva',
        doctorEmail: 'ana.silva@clinica.com',
        doctorPhone: '(11) 99999-0002',
        date: '2024-01-25',
        time: '14:30',
        status: 'scheduled',
        symptoms: 'Dor nas costas',
      },
    ],
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    _id: 'p2',
    name: 'João Santos',
    email: 'joao@email.com',
    phone: '(11) 99999-2222',
    dateOfBirth: '1978-07-22',
    gender: 'male',
    address: 'Av. Paulista, 456 - São Paulo, SP',
    bloodType: 'O+',
    height: 178,
    weight: 75,
    emergencyContact: {
      name: 'Ana Santos',
      phone: '(11) 99999-1111',
      relationship: 'Esposa',
    },
    medicalHistory: [
      {
        _id: 'mh3',
        date: '2024-01-15',
        diagnosis: 'Gastrite',
        treatment: 'Dieta e medicação',
        prescription: 'Omeprazol 20mg - 1 comprimido ao dia por 30 dias',
        notes:
          'Paciente com histórico de gastrite. Recomendado evitar alimentos ácidos.',
        doctor: 'Dr. Carlos Mendes',
        createdAt: '2024-01-15T14:30:00Z',
      },
    ],
    consultations: [
      {
        _id: 'c3',
        patientName: 'João Santos',
        patientEmail: 'joao@email.com',
        doctorName: 'Dr. Carlos Mendes',
        doctorEmail: 'carlos.mendes@clinica.com',
        doctorPhone: '(11) 99999-0001',
        date: '2024-01-15',
        time: '14:30',
        status: 'scheduled',
        symptoms: 'Dor abdominal, náuseas',
      },
    ],
    createdAt: '2023-02-20T14:30:00Z',
  },
  {
    _id: 'p3',
    name: 'Ana Costa',
    email: 'ana@email.com',
    phone: '(11) 99999-3333',
    dateOfBirth: '1992-11-08',
    gender: 'female',
    address: 'Rua Augusta, 789 - São Paulo, SP',
    bloodType: 'B+',
    height: 160,
    weight: 55,
    emergencyContact: {
      name: 'Pedro Costa',
      phone: '(11) 99999-2222',
      relationship: 'Irmão',
    },
    medicalHistory: [],
    consultations: [
      {
        _id: 'c4',
        patientName: 'Ana Costa',
        patientEmail: 'ana@email.com',
        doctorName: 'Dr. Pedro Santos',
        doctorEmail: 'pedro.santos@clinica.com',
        doctorPhone: '(11) 99999-0003',
        date: '2024-01-16',
        time: '10:00',
        status: 'confirmed',
        symptoms: 'Febre, tosse seca',
      },
    ],
    createdAt: '2023-03-10T09:15:00Z',
  },
  {
    _id: 'p4',
    name: 'Pedro Oliveira',
    email: 'pedro@email.com',
    phone: '(11) 99999-4444',
    dateOfBirth: '1980-05-12',
    gender: 'male',
    address: 'Rua Oscar Freire, 321 - São Paulo, SP',
    bloodType: 'AB+',
    height: 182,
    weight: 80,
    emergencyContact: {
      name: 'Lucia Oliveira',
      phone: '(11) 99999-3333',
      relationship: 'Esposa',
    },
    medicalHistory: [
      {
        _id: 'mh4',
        date: '2023-11-20',
        diagnosis: 'Hérnia de disco',
        treatment: 'Fisioterapia e medicação',
        prescription:
          'Diclofenaco 50mg - 1 comprimido a cada 8 horas por 7 dias',
        notes:
          'Paciente com dor lombar intensa. Encaminhado para fisioterapia.',
        doctor: 'Dr. Carlos Mendes',
        createdAt: '2023-11-20T16:00:00Z',
      },
    ],
    consultations: [
      {
        _id: 'c5',
        patientName: 'Pedro Oliveira',
        patientEmail: 'pedro@email.com',
        doctorName: 'Dr. Lucia Ferreira',
        doctorEmail: 'lucia.ferreira@clinica.com',
        doctorPhone: '(11) 99999-0004',
        date: '2024-01-17',
        time: '16:00',
        status: 'scheduled',
        symptoms: 'Dor nas costas, dificuldade para dormir',
      },
    ],
    createdAt: '2023-04-05T16:45:00Z',
  },
  {
    _id: 'p5',
    name: 'Lucia Ferreira',
    email: 'lucia@email.com',
    phone: '(11) 99999-5555',
    dateOfBirth: '1975-09-30',
    gender: 'female',
    address: 'Rua Haddock Lobo, 654 - São Paulo, SP',
    bloodType: 'A-',
    height: 158,
    weight: 58,
    emergencyContact: {
      name: 'Roberto Ferreira',
      phone: '(11) 99999-4444',
      relationship: 'Filho',
    },
    medicalHistory: [
      {
        _id: 'mh5',
        date: '2023-10-15',
        diagnosis: 'Hipertensão arterial',
        treatment: 'Medicação contínua',
        prescription: 'Losartana 50mg - 1 comprimido ao dia',
        notes:
          'Paciente com pressão arterial elevada. Acompanhamento mensal necessário.',
        doctor: 'Dr. Carlos Mendes',
        createdAt: '2023-10-15T11:00:00Z',
      },
    ],
    consultations: [
      {
        _id: 'c6',
        patientName: 'Lucia Ferreira',
        patientEmail: 'lucia@email.com',
        doctorName: 'Dr. Roberto Costa',
        doctorEmail: 'roberto.costa@clinica.com',
        doctorPhone: '(11) 99999-0005',
        date: '2024-01-14',
        time: '11:00',
        status: 'cancelled',
        symptoms: 'Dor de cabeça',
        notes: 'Paciente cancelou por motivos pessoais',
      },
    ],
    createdAt: '2023-05-12T11:20:00Z',
  },
  {
    _id: 'p6',
    name: 'Carlos Mendes',
    email: 'carlos@email.com',
    phone: '(11) 99999-6666',
    dateOfBirth: '1988-12-03',
    gender: 'male',
    address: 'Av. Brigadeiro Faria Lima, 987 - São Paulo, SP',
    bloodType: 'O-',
    height: 175,
    weight: 70,
    emergencyContact: {
      name: 'Fernanda Mendes',
      phone: '(11) 99999-5555',
      relationship: 'Esposa',
    },
    medicalHistory: [],
    consultations: [
      {
        _id: 'c7',
        patientName: 'Carlos Mendes',
        patientEmail: 'carlos@email.com',
        doctorName: 'Dr. Fernanda Lima',
        doctorEmail: 'fernanda.lima@clinica.com',
        doctorPhone: '(11) 99999-0006',
        date: '2024-01-18',
        time: '08:30',
        status: 'scheduled',
        symptoms: 'Dor no peito, falta de ar',
      },
    ],
    createdAt: '2023-06-18T13:10:00Z',
  },
];

// ===== DADOS MOCKADOS DE MÉDICOS =====

export const MOCK_DOCTORS = [
  {
    _id: 'd1',
    name: 'Dr. Carlos Mendes',
    email: 'carlos.mendes@clinica.com',
    phone: '(11) 99999-0001',
    specialty: 'Clínico Geral',
    crm: 'CRM-SP 12345',
    avatar: 'CM',
    rating: 4.8,
    totalConsultations: 1250,
    availableSlots: [
      { date: '2024-01-20', time: '09:00', available: true },
      { date: '2024-01-20', time: '10:00', available: true },
      { date: '2024-01-20', time: '14:00', available: false },
      { date: '2024-01-20', time: '15:00', available: true },
      { date: '2024-01-21', time: '08:00', available: true },
      { date: '2024-01-21', time: '09:00', available: true },
      { date: '2024-01-21', time: '16:00', available: true },
      { date: '2024-01-22', time: '10:00', available: true },
      { date: '2024-01-22', time: '11:00', available: true },
      { date: '2024-01-22', time: '14:00', available: true },
    ],
  },
  {
    _id: 'd2',
    name: 'Dra. Ana Silva',
    email: 'ana.silva@clinica.com',
    phone: '(11) 99999-0002',
    specialty: 'Cardiologia',
    crm: 'CRM-SP 23456',
    avatar: 'AS',
    rating: 4.9,
    totalConsultations: 890,
    availableSlots: [
      { date: '2024-01-20', time: '08:00', available: true },
      { date: '2024-01-20', time: '11:00', available: true },
      { date: '2024-01-20', time: '15:00', available: true },
      { date: '2024-01-21', time: '09:00', available: false },
      { date: '2024-01-21', time: '10:00', available: true },
      { date: '2024-01-21', time: '14:00', available: true },
      { date: '2024-01-22', time: '08:00', available: true },
      { date: '2024-01-22', time: '09:00', available: true },
      { date: '2024-01-22', time: '16:00', available: true },
    ],
  },
  {
    _id: 'd3',
    name: 'Dr. Pedro Santos',
    email: 'pedro.santos@clinica.com',
    phone: '(11) 99999-0003',
    specialty: 'Ortopedia',
    crm: 'CRM-SP 34567',
    avatar: 'PS',
    rating: 4.7,
    totalConsultations: 1100,
    availableSlots: [
      { date: '2024-01-20', time: '10:00', available: true },
      { date: '2024-01-20', time: '11:00', available: true },
      { date: '2024-01-20', time: '16:00', available: true },
      { date: '2024-01-21', time: '08:00', available: true },
      { date: '2024-01-21', time: '14:00', available: true },
      { date: '2024-01-21', time: '15:00', available: true },
      { date: '2024-01-22', time: '09:00', available: true },
      { date: '2024-01-22', time: '10:00', available: true },
      { date: '2024-01-22', time: '11:00', available: true },
    ],
  },
  {
    _id: 'd4',
    name: 'Dra. Lucia Ferreira',
    email: 'lucia.ferreira@clinica.com',
    phone: '(11) 99999-0004',
    specialty: 'Dermatologia',
    crm: 'CRM-SP 45678',
    avatar: 'LF',
    rating: 4.6,
    totalConsultations: 750,
    availableSlots: [
      { date: '2024-01-20', time: '08:00', available: true },
      { date: '2024-01-20', time: '09:00', available: true },
      { date: '2024-01-20', time: '14:00', available: true },
      { date: '2024-01-21', time: '10:00', available: true },
      { date: '2024-01-21', time: '11:00', available: true },
      { date: '2024-01-21', time: '16:00', available: true },
      { date: '2024-01-22', time: '08:00', available: true },
      { date: '2024-01-22', time: '14:00', available: true },
      { date: '2024-01-22', time: '15:00', available: true },
    ],
  },
  {
    _id: 'd5',
    name: 'Dr. Roberto Costa',
    email: 'roberto.costa@clinica.com',
    phone: '(11) 99999-0005',
    specialty: 'Gastroenterologia',
    crm: 'CRM-SP 56789',
    avatar: 'RC',
    rating: 4.5,
    totalConsultations: 680,
    availableSlots: [
      { date: '2024-01-20', time: '09:00', available: true },
      { date: '2024-01-20', time: '10:00', available: true },
      { date: '2024-01-20', time: '15:00', available: true },
      { date: '2024-01-21', time: '08:00', available: true },
      { date: '2024-01-21', time: '09:00', available: true },
      { date: '2024-01-21', time: '14:00', available: true },
      { date: '2024-01-22', time: '10:00', available: true },
      { date: '2024-01-22', time: '11:00', available: true },
      { date: '2024-01-22', time: '16:00', available: true },
    ],
  },
  {
    _id: 'd6',
    name: 'Dra. Fernanda Lima',
    email: 'fernanda.lima@clinica.com',
    phone: '(11) 99999-0006',
    specialty: 'Neurologia',
    crm: 'CRM-SP 67890',
    avatar: 'FL',
    rating: 4.9,
    totalConsultations: 920,
    availableSlots: [
      { date: '2024-01-20', time: '08:00', available: true },
      { date: '2024-01-20', time: '11:00', available: true },
      { date: '2024-01-20', time: '16:00', available: true },
      { date: '2024-01-21', time: '09:00', available: true },
      { date: '2024-01-21', time: '10:00', available: true },
      { date: '2024-01-21', time: '15:00', available: true },
      { date: '2024-01-22', time: '08:00', available: true },
      { date: '2024-01-22', time: '14:00', available: true },
      { date: '2024-01-22', time: '15:00', available: true },
    ],
  },
];

// ===== DADOS MOCKADOS DE HISTÓRICO MÉDICO =====

export const MOCK_MEDICAL_RECORDS = [
  {
    _id: '1',
    date: '2024-01-15',
    diagnosis: 'Cefaleia tensional',
    treatment: 'Analgésicos e relaxamento muscular',
    prescription: 'Paracetamol 500mg - 1 comprimido a cada 6 horas por 3 dias',
    notes:
      'Paciente relatou dor de cabeça persistente há 3 dias. Recomendado evitar estresse e praticar exercícios de relaxamento.',
    doctor: 'Dr. Carlos Mendes',
    doctorEmail: 'carlos.mendes@clinica.com',
    doctorPhone: '(11) 99999-0001',
    symptoms: 'Dor de cabeça, tensão muscular, irritabilidade',
    vitalSigns: {
      bloodPressure: '120/80 mmHg',
      heartRate: '72 bpm',
      temperature: '36.8°C',
      weight: '70 kg',
    },
    exams: ['Hemograma completo', 'Glicemia em jejum'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    _id: '2',
    date: '2023-12-10',
    diagnosis: 'Resfriado comum',
    treatment: 'Repouso e hidratação',
    prescription: 'Vitamina C e paracetamol conforme necessário',
    notes:
      'Sintomas leves, sem complicações. Paciente orientado sobre cuidados básicos.',
    doctor: 'Dr. Ana Silva',
    doctorEmail: 'ana.silva@clinica.com',
    doctorPhone: '(11) 99999-0002',
    symptoms: 'Febre, tosse seca, coriza, dor de garganta',
    vitalSigns: {
      bloodPressure: '118/78 mmHg',
      heartRate: '76 bpm',
      temperature: '37.2°C',
      weight: '70 kg',
    },
    createdAt: '2023-12-10T14:30:00Z',
  },
  {
    _id: '3',
    date: '2023-11-20',
    diagnosis: 'Hérnia de disco L4-L5',
    treatment: 'Fisioterapia e medicação',
    prescription: 'Diclofenaco 50mg - 1 comprimido a cada 8 horas por 7 dias',
    notes:
      'Paciente com dor lombar intensa. Encaminhado para fisioterapia e reavaliação em 30 dias.',
    doctor: 'Dr. Pedro Santos',
    doctorEmail: 'pedro.santos@clinica.com',
    doctorPhone: '(11) 99999-0003',
    symptoms:
      'Dor nas costas, dificuldade para dormir, irradiação para membro inferior',
    vitalSigns: {
      bloodPressure: '125/82 mmHg',
      heartRate: '74 bpm',
      temperature: '36.9°C',
      weight: '71 kg',
    },
    exams: ['Ressonância magnética da coluna lombar'],
    createdAt: '2023-11-20T16:00:00Z',
  },
  {
    _id: '4',
    date: '2023-10-15',
    diagnosis: 'Hipertensão arterial',
    treatment: 'Medicação contínua e mudança de hábitos',
    prescription: 'Losartana 50mg - 1 comprimido ao dia',
    notes:
      'Paciente com pressão arterial elevada. Acompanhamento mensal necessário. Orientado sobre dieta e exercícios.',
    doctor: 'Dr. Lucia Ferreira',
    doctorEmail: 'lucia.ferreira@clinica.com',
    doctorPhone: '(11) 99999-0004',
    symptoms: 'Dor de cabeça, tontura, cansaço',
    vitalSigns: {
      bloodPressure: '150/95 mmHg',
      heartRate: '78 bpm',
      temperature: '36.7°C',
      weight: '72 kg',
    },
    exams: ['Hemograma completo', 'Creatinina', 'Glicemia', 'Colesterol total'],
    createdAt: '2023-10-15T11:00:00Z',
  },
  {
    _id: '5',
    date: '2023-09-05',
    diagnosis: 'Gastrite',
    treatment: 'Dieta e medicação',
    prescription: 'Omeprazol 20mg - 1 comprimido ao dia por 30 dias',
    notes:
      'Paciente com histórico de gastrite. Recomendado evitar alimentos ácidos e refeições pesadas.',
    doctor: 'Dr. Roberto Costa',
    doctorEmail: 'roberto.costa@clinica.com',
    doctorPhone: '(11) 99999-0005',
    symptoms: 'Dor abdominal, náuseas, azia',
    vitalSigns: {
      bloodPressure: '122/80 mmHg',
      heartRate: '72 bpm',
      temperature: '36.8°C',
      weight: '71 kg',
    },
    exams: ['Endoscopia digestiva alta'],
    createdAt: '2023-09-05T09:30:00Z',
  },
];

export const MOCK_MEDICAL_RECORDS_ADMIN = [
  {
    _id: '1',
    patient: {
      name: 'João Silva',
      email: 'joao@email.com',
      dateOfBirth: '1985-03-15',
    },
    doctor: { name: 'Dr. Maria Santos', email: 'maria@clinic.com' },
    consultationDate: '2024-01-15',
    diagnosis: 'Hipertensão arterial leve',
    prescription: 'Losartana 50mg - 1 comprimido ao dia',
    notes:
      'Paciente apresentou pressão arterial elevada. Recomendado controle de sal e exercícios físicos.',
    status: 'active',
  },
  {
    _id: '2',
    patient: {
      name: 'Ana Costa',
      email: 'ana@email.com',
      dateOfBirth: '1990-07-22',
    },
    doctor: { name: 'Dr. Carlos Oliveira', email: 'carlos@clinic.com' },
    consultationDate: '2024-01-10',
    diagnosis: 'Resfriado comum',
    prescription: 'Paracetamol 500mg - 1 comprimido a cada 6h',
    notes:
      'Sintomas leves, sem complicações. Recomendado repouso e hidratação.',
    status: 'resolved',
  },
  {
    _id: '3',
    patient: {
      name: 'Pedro Lima',
      email: 'pedro@email.com',
      dateOfBirth: '1978-11-08',
    },
    doctor: { name: 'Dr. Maria Santos', email: 'maria@clinic.com' },
    consultationDate: '2024-01-08',
    diagnosis: 'Diabetes tipo 2',
    prescription: 'Metformina 850mg - 2x ao dia',
    notes:
      'Paciente diagnosticado com diabetes. Iniciado tratamento e orientações sobre dieta.',
    status: 'follow_up',
  },
];

// ===== DADOS MOCKADOS DE PERFIL =====

export const MOCK_PATIENT_PROFILE = {
  _id: '1',
  name: 'Maria Silva',
  email: 'maria@email.com',
  phone: '(11) 99999-1111',
  dateOfBirth: '1985-03-15',
  gender: 'female',
  address: 'Rua das Flores, 123 - São Paulo, SP',
  bloodType: 'A+',
  height: 165,
  weight: 62,
  emergencyContact: {
    name: 'João Silva',
    phone: '(11) 99999-0000',
    relationship: 'Esposo',
  },
  preferences: {
    notifications: true,
    emailNotifications: true,
    smsNotifications: false,
  },
};

// ===== DADOS MOCKADOS DE DASHBOARD =====

export const MOCK_CONSULTATION_REMINDERS = [
  {
    id: '1',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    date: '2024-01-15',
    time: '09:00',
    type: 'today',
    status: 'confirmed',
  },
  {
    id: '2',
    patientName: 'João Santos',
    patientEmail: 'joao@email.com',
    date: '2024-01-15',
    time: '14:30',
    type: 'today',
    status: 'scheduled',
  },
  {
    id: '3',
    patientName: 'Ana Costa',
    patientEmail: 'ana@email.com',
    date: '2024-01-16',
    time: '10:00',
    type: 'tomorrow',
    status: 'confirmed',
  },
  {
    id: '4',
    patientName: 'Pedro Oliveira',
    patientEmail: 'pedro@email.com',
    date: '2024-01-17',
    time: '16:00',
    type: 'upcoming',
    status: 'pending',
  },
  {
    id: '5',
    patientName: 'Lucia Ferreira',
    patientEmail: 'lucia@email.com',
    date: '2024-01-14',
    time: '11:00',
    type: 'overdue',
    status: 'scheduled',
  },
];

// ===== DADOS MOCKADOS DE CONSULTAS DO PACIENTE (DASHBOARD) =====

export const MOCK_PATIENT_CONSULTATIONS = [
  {
    _id: '1',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    doctorName: 'Dr. Carlos Mendes',
    doctorEmail: 'carlos.mendes@clinica.com',
    doctorPhone: '(11) 99999-0001',
    date: '2024-01-15',
    time: '09:00',
    status: 'completed',
    symptoms: 'Dor de cabeça, tensão muscular',
    notes: 'Consulta realizada com sucesso',
    diagnosis: 'Cefaleia tensional',
    prescription: 'Paracetamol 500mg - 1 comprimido a cada 6 horas por 3 dias',
  },
  {
    _id: '2',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    doctorName: 'Dr. Ana Silva',
    doctorEmail: 'ana.silva@clinica.com',
    doctorPhone: '(11) 99999-0002',
    date: '2024-01-20',
    time: '14:30',
    status: 'scheduled',
    symptoms: 'Dor nas costas',
  },
  {
    _id: '3',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    doctorName: 'Dr. Pedro Santos',
    doctorEmail: 'pedro.santos@clinica.com',
    doctorPhone: '(11) 99999-0003',
    date: '2024-01-25',
    time: '10:00',
    status: 'confirmed',
    symptoms: 'Febre, tosse seca',
  },
  {
    _id: '4',
    patientName: 'Maria Silva',
    patientEmail: 'maria@email.com',
    doctorName: 'Dr. Lucia Ferreira',
    doctorEmail: 'lucia.ferreira@clinica.com',
    doctorPhone: '(11) 99999-0004',
    date: '2024-01-30',
    time: '16:00',
    status: 'scheduled',
    symptoms: 'Dor abdominal',
  },
];

export const MOCK_PATIENT_MEDICAL_RECORDS = [
  {
    _id: '1',
    date: '2024-01-15',
    diagnosis: 'Cefaleia tensional',
    treatment: 'Analgésicos e relaxamento muscular',
    prescription: 'Paracetamol 500mg - 1 comprimido a cada 6 horas por 3 dias',
    doctor: 'Dr. Carlos Mendes',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    _id: '2',
    date: '2023-12-10',
    diagnosis: 'Resfriado comum',
    treatment: 'Repouso e hidratação',
    prescription: 'Vitamina C e paracetamol conforme necessário',
    doctor: 'Dr. Ana Silva',
    createdAt: '2023-12-10T14:30:00Z',
  },
  {
    _id: '3',
    date: '2023-11-20',
    diagnosis: 'Hérnia de disco',
    treatment: 'Fisioterapia e medicação',
    prescription: 'Diclofenaco 50mg - 1 comprimido a cada 8 horas por 7 dias',
    doctor: 'Dr. Pedro Santos',
    createdAt: '2023-11-20T16:00:00Z',
  },
];
